[package]
name = "auralis-store"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
auralis-core = { path = "../auralis-core" }
auralis-config = { path = "../auralis-config" }
redb = "4.3"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
walkdir = "2.5"

[dev-dependencies]
tempfile = { workspace = true }
